/*
 * Generated by gdbus-codegen 2.50.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "screensaver-dbus.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.gnome.ScreenSaver
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:AADBusGnomeScreenSaver
 * @title: AADBusGnomeScreenSaver
 * @short_description: Generated C code for the org.gnome.ScreenSaver D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.gnome.ScreenSaver ---- */

static const _ExtendedGDBusArgInfo _aa_dbus_gnome_screen_saver_signal_info_active_changed_ARG_active =
{
  {
    -1,
    (gchar *) "active",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _aa_dbus_gnome_screen_saver_signal_info_active_changed_ARG_pointers[] =
{
  &_aa_dbus_gnome_screen_saver_signal_info_active_changed_ARG_active,
  NULL
};

static const _ExtendedGDBusSignalInfo _aa_dbus_gnome_screen_saver_signal_info_active_changed =
{
  {
    -1,
    (gchar *) "ActiveChanged",
    (GDBusArgInfo **) &_aa_dbus_gnome_screen_saver_signal_info_active_changed_ARG_pointers,
    NULL
  },
  "active-changed"
};

static const _ExtendedGDBusSignalInfo * const _aa_dbus_gnome_screen_saver_signal_info_pointers[] =
{
  &_aa_dbus_gnome_screen_saver_signal_info_active_changed,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _aa_dbus_gnome_screen_saver_interface_info =
{
  {
    -1,
    (gchar *) "org.gnome.ScreenSaver",
    NULL,
    (GDBusSignalInfo **) &_aa_dbus_gnome_screen_saver_signal_info_pointers,
    NULL,
    NULL
  },
  "gnome-screen-saver",
};


/**
 * aa_dbus_gnome_screen_saver_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
aa_dbus_gnome_screen_saver_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_aa_dbus_gnome_screen_saver_interface_info.parent_struct;
}

/**
 * aa_dbus_gnome_screen_saver_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #AADBusGnomeScreenSaver interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
aa_dbus_gnome_screen_saver_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * AADBusGnomeScreenSaver:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>.
 */

/**
 * AADBusGnomeScreenSaverIface:
 * @parent_iface: The parent interface.
 * @active_changed: Handler for the #AADBusGnomeScreenSaver::active-changed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>.
 */

typedef AADBusGnomeScreenSaverIface AADBusGnomeScreenSaverInterface;
G_DEFINE_INTERFACE (AADBusGnomeScreenSaver, aa_dbus_gnome_screen_saver, G_TYPE_OBJECT);

static void
aa_dbus_gnome_screen_saver_default_init (AADBusGnomeScreenSaverIface *iface)
{
  /* GObject signals for received D-Bus signals: */
  /**
   * AADBusGnomeScreenSaver::active-changed:
   * @object: A #AADBusGnomeScreenSaver.
   * @arg_active: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-gnome-ScreenSaver.ActiveChanged">"ActiveChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("active-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (AADBusGnomeScreenSaverIface, active_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_BOOLEAN);

}

/**
 * aa_dbus_gnome_screen_saver_emit_active_changed:
 * @object: A #AADBusGnomeScreenSaver.
 * @arg_active: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-gnome-ScreenSaver.ActiveChanged">"ActiveChanged"</link> D-Bus signal.
 */
void
aa_dbus_gnome_screen_saver_emit_active_changed (
    AADBusGnomeScreenSaver *object,
    gboolean arg_active)
{
  g_signal_emit_by_name (object, "active-changed", arg_active);
}

/* ------------------------------------------------------------------------ */

/**
 * AADBusGnomeScreenSaverProxy:
 *
 * The #AADBusGnomeScreenSaverProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * AADBusGnomeScreenSaverProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #AADBusGnomeScreenSaverProxy.
 */

struct _AADBusGnomeScreenSaverProxyPrivate
{
  GData *qdata;
};

static void aa_dbus_gnome_screen_saver_proxy_iface_init (AADBusGnomeScreenSaverIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (AADBusGnomeScreenSaverProxy, aa_dbus_gnome_screen_saver_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (AADBusGnomeScreenSaverProxy)
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_GNOME_SCREEN_SAVER, aa_dbus_gnome_screen_saver_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (AADBusGnomeScreenSaverProxy, aa_dbus_gnome_screen_saver_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_GNOME_SCREEN_SAVER, aa_dbus_gnome_screen_saver_proxy_iface_init));

#endif
static void
aa_dbus_gnome_screen_saver_proxy_finalize (GObject *object)
{
  AADBusGnomeScreenSaverProxy *proxy = AA_DBUS_GNOME_SCREEN_SAVER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (aa_dbus_gnome_screen_saver_proxy_parent_class)->finalize (object);
}

static void
aa_dbus_gnome_screen_saver_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
aa_dbus_gnome_screen_saver_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
aa_dbus_gnome_screen_saver_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_aa_dbus_gnome_screen_saver_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], AA_DBUS_TYPE_GNOME_SCREEN_SAVER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, AA_DBUS_TYPE_GNOME_SCREEN_SAVER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
aa_dbus_gnome_screen_saver_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  AADBusGnomeScreenSaverProxy *proxy = AA_DBUS_GNOME_SCREEN_SAVER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_aa_dbus_gnome_screen_saver_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_aa_dbus_gnome_screen_saver_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
aa_dbus_gnome_screen_saver_proxy_init (AADBusGnomeScreenSaverProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = aa_dbus_gnome_screen_saver_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, AA_DBUS_TYPE_GNOME_SCREEN_SAVER_PROXY, AADBusGnomeScreenSaverProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), aa_dbus_gnome_screen_saver_interface_info ());
}

static void
aa_dbus_gnome_screen_saver_proxy_class_init (AADBusGnomeScreenSaverProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = aa_dbus_gnome_screen_saver_proxy_finalize;
  gobject_class->get_property = aa_dbus_gnome_screen_saver_proxy_get_property;
  gobject_class->set_property = aa_dbus_gnome_screen_saver_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = aa_dbus_gnome_screen_saver_proxy_g_signal;
  proxy_class->g_properties_changed = aa_dbus_gnome_screen_saver_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (AADBusGnomeScreenSaverProxyPrivate));
#endif
}

static void
aa_dbus_gnome_screen_saver_proxy_iface_init (AADBusGnomeScreenSaverIface *iface)
{
}

/**
 * aa_dbus_gnome_screen_saver_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call aa_dbus_gnome_screen_saver_proxy_new_finish() to get the result of the operation.
 *
 * See aa_dbus_gnome_screen_saver_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
aa_dbus_gnome_screen_saver_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (AA_DBUS_TYPE_GNOME_SCREEN_SAVER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.ScreenSaver", NULL);
}

/**
 * aa_dbus_gnome_screen_saver_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to aa_dbus_gnome_screen_saver_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with aa_dbus_gnome_screen_saver_proxy_new().
 *
 * Returns: (transfer full) (type AADBusGnomeScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
AADBusGnomeScreenSaver *
aa_dbus_gnome_screen_saver_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return AA_DBUS_GNOME_SCREEN_SAVER (ret);
  else
    return NULL;
}

/**
 * aa_dbus_gnome_screen_saver_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See aa_dbus_gnome_screen_saver_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type AADBusGnomeScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
AADBusGnomeScreenSaver *
aa_dbus_gnome_screen_saver_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (AA_DBUS_TYPE_GNOME_SCREEN_SAVER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.ScreenSaver", NULL);
  if (ret != NULL)
    return AA_DBUS_GNOME_SCREEN_SAVER (ret);
  else
    return NULL;
}


/**
 * aa_dbus_gnome_screen_saver_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like aa_dbus_gnome_screen_saver_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call aa_dbus_gnome_screen_saver_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See aa_dbus_gnome_screen_saver_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
aa_dbus_gnome_screen_saver_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (AA_DBUS_TYPE_GNOME_SCREEN_SAVER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.ScreenSaver", NULL);
}

/**
 * aa_dbus_gnome_screen_saver_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to aa_dbus_gnome_screen_saver_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with aa_dbus_gnome_screen_saver_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type AADBusGnomeScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
AADBusGnomeScreenSaver *
aa_dbus_gnome_screen_saver_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return AA_DBUS_GNOME_SCREEN_SAVER (ret);
  else
    return NULL;
}

/**
 * aa_dbus_gnome_screen_saver_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like aa_dbus_gnome_screen_saver_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See aa_dbus_gnome_screen_saver_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type AADBusGnomeScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
AADBusGnomeScreenSaver *
aa_dbus_gnome_screen_saver_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (AA_DBUS_TYPE_GNOME_SCREEN_SAVER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.ScreenSaver", NULL);
  if (ret != NULL)
    return AA_DBUS_GNOME_SCREEN_SAVER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * AADBusGnomeScreenSaverSkeleton:
 *
 * The #AADBusGnomeScreenSaverSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * AADBusGnomeScreenSaverSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #AADBusGnomeScreenSaverSkeleton.
 */

struct _AADBusGnomeScreenSaverSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_aa_dbus_gnome_screen_saver_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  AADBusGnomeScreenSaverSkeleton *skeleton = AA_DBUS_GNOME_SCREEN_SAVER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], AA_DBUS_TYPE_GNOME_SCREEN_SAVER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, AA_DBUS_TYPE_GNOME_SCREEN_SAVER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_aa_dbus_gnome_screen_saver_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  AADBusGnomeScreenSaverSkeleton *skeleton = AA_DBUS_GNOME_SCREEN_SAVER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_aa_dbus_gnome_screen_saver_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_aa_dbus_gnome_screen_saver_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  AADBusGnomeScreenSaverSkeleton *skeleton = AA_DBUS_GNOME_SCREEN_SAVER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_aa_dbus_gnome_screen_saver_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _aa_dbus_gnome_screen_saver_skeleton_vtable =
{
  _aa_dbus_gnome_screen_saver_skeleton_handle_method_call,
  _aa_dbus_gnome_screen_saver_skeleton_handle_get_property,
  _aa_dbus_gnome_screen_saver_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
aa_dbus_gnome_screen_saver_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return aa_dbus_gnome_screen_saver_interface_info ();
}

static GDBusInterfaceVTable *
aa_dbus_gnome_screen_saver_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_aa_dbus_gnome_screen_saver_skeleton_vtable;
}

static GVariant *
aa_dbus_gnome_screen_saver_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  AADBusGnomeScreenSaverSkeleton *skeleton = AA_DBUS_GNOME_SCREEN_SAVER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_aa_dbus_gnome_screen_saver_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _aa_dbus_gnome_screen_saver_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _aa_dbus_gnome_screen_saver_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _aa_dbus_gnome_screen_saver_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gnome.ScreenSaver", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
aa_dbus_gnome_screen_saver_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_aa_dbus_gnome_screen_saver_on_signal_active_changed (
    AADBusGnomeScreenSaver *object,
    gboolean arg_active)
{
  AADBusGnomeScreenSaverSkeleton *skeleton = AA_DBUS_GNOME_SCREEN_SAVER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(b)",
                   arg_active));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gnome.ScreenSaver", "ActiveChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void aa_dbus_gnome_screen_saver_skeleton_iface_init (AADBusGnomeScreenSaverIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (AADBusGnomeScreenSaverSkeleton, aa_dbus_gnome_screen_saver_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (AADBusGnomeScreenSaverSkeleton)
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_GNOME_SCREEN_SAVER, aa_dbus_gnome_screen_saver_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (AADBusGnomeScreenSaverSkeleton, aa_dbus_gnome_screen_saver_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_GNOME_SCREEN_SAVER, aa_dbus_gnome_screen_saver_skeleton_iface_init));

#endif
static void
aa_dbus_gnome_screen_saver_skeleton_finalize (GObject *object)
{
  AADBusGnomeScreenSaverSkeleton *skeleton = AA_DBUS_GNOME_SCREEN_SAVER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (aa_dbus_gnome_screen_saver_skeleton_parent_class)->finalize (object);
}

static void
aa_dbus_gnome_screen_saver_skeleton_init (AADBusGnomeScreenSaverSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = aa_dbus_gnome_screen_saver_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, AA_DBUS_TYPE_GNOME_SCREEN_SAVER_SKELETON, AADBusGnomeScreenSaverSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
aa_dbus_gnome_screen_saver_skeleton_class_init (AADBusGnomeScreenSaverSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = aa_dbus_gnome_screen_saver_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = aa_dbus_gnome_screen_saver_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = aa_dbus_gnome_screen_saver_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = aa_dbus_gnome_screen_saver_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = aa_dbus_gnome_screen_saver_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (AADBusGnomeScreenSaverSkeletonPrivate));
#endif
}

static void
aa_dbus_gnome_screen_saver_skeleton_iface_init (AADBusGnomeScreenSaverIface *iface)
{
  iface->active_changed = _aa_dbus_gnome_screen_saver_on_signal_active_changed;
}

/**
 * aa_dbus_gnome_screen_saver_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>.
 *
 * Returns: (transfer full) (type AADBusGnomeScreenSaverSkeleton): The skeleton object.
 */
AADBusGnomeScreenSaver *
aa_dbus_gnome_screen_saver_skeleton_new (void)
{
  return AA_DBUS_GNOME_SCREEN_SAVER (g_object_new (AA_DBUS_TYPE_GNOME_SCREEN_SAVER_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for interface org.freedesktop.ScreenSaver
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:AADBusFreedesktopScreenSaver
 * @title: AADBusFreedesktopScreenSaver
 * @short_description: Generated C code for the org.freedesktop.ScreenSaver D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.freedesktop.ScreenSaver ---- */

static const _ExtendedGDBusArgInfo _aa_dbus_freedesktop_screen_saver_signal_info_active_changed_ARG_active =
{
  {
    -1,
    (gchar *) "active",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _aa_dbus_freedesktop_screen_saver_signal_info_active_changed_ARG_pointers[] =
{
  &_aa_dbus_freedesktop_screen_saver_signal_info_active_changed_ARG_active,
  NULL
};

static const _ExtendedGDBusSignalInfo _aa_dbus_freedesktop_screen_saver_signal_info_active_changed =
{
  {
    -1,
    (gchar *) "ActiveChanged",
    (GDBusArgInfo **) &_aa_dbus_freedesktop_screen_saver_signal_info_active_changed_ARG_pointers,
    NULL
  },
  "active-changed"
};

static const _ExtendedGDBusSignalInfo * const _aa_dbus_freedesktop_screen_saver_signal_info_pointers[] =
{
  &_aa_dbus_freedesktop_screen_saver_signal_info_active_changed,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _aa_dbus_freedesktop_screen_saver_interface_info =
{
  {
    -1,
    (gchar *) "org.freedesktop.ScreenSaver",
    NULL,
    (GDBusSignalInfo **) &_aa_dbus_freedesktop_screen_saver_signal_info_pointers,
    NULL,
    NULL
  },
  "freedesktop-screen-saver",
};


/**
 * aa_dbus_freedesktop_screen_saver_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
aa_dbus_freedesktop_screen_saver_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_aa_dbus_freedesktop_screen_saver_interface_info.parent_struct;
}

/**
 * aa_dbus_freedesktop_screen_saver_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #AADBusFreedesktopScreenSaver interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
aa_dbus_freedesktop_screen_saver_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * AADBusFreedesktopScreenSaver:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link>.
 */

/**
 * AADBusFreedesktopScreenSaverIface:
 * @parent_iface: The parent interface.
 * @active_changed: Handler for the #AADBusFreedesktopScreenSaver::active-changed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link>.
 */

typedef AADBusFreedesktopScreenSaverIface AADBusFreedesktopScreenSaverInterface;
G_DEFINE_INTERFACE (AADBusFreedesktopScreenSaver, aa_dbus_freedesktop_screen_saver, G_TYPE_OBJECT);

static void
aa_dbus_freedesktop_screen_saver_default_init (AADBusFreedesktopScreenSaverIface *iface)
{
  /* GObject signals for received D-Bus signals: */
  /**
   * AADBusFreedesktopScreenSaver::active-changed:
   * @object: A #AADBusFreedesktopScreenSaver.
   * @arg_active: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-freedesktop-ScreenSaver.ActiveChanged">"ActiveChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("active-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (AADBusFreedesktopScreenSaverIface, active_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_BOOLEAN);

}

/**
 * aa_dbus_freedesktop_screen_saver_emit_active_changed:
 * @object: A #AADBusFreedesktopScreenSaver.
 * @arg_active: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-freedesktop-ScreenSaver.ActiveChanged">"ActiveChanged"</link> D-Bus signal.
 */
void
aa_dbus_freedesktop_screen_saver_emit_active_changed (
    AADBusFreedesktopScreenSaver *object,
    gboolean arg_active)
{
  g_signal_emit_by_name (object, "active-changed", arg_active);
}

/* ------------------------------------------------------------------------ */

/**
 * AADBusFreedesktopScreenSaverProxy:
 *
 * The #AADBusFreedesktopScreenSaverProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * AADBusFreedesktopScreenSaverProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #AADBusFreedesktopScreenSaverProxy.
 */

struct _AADBusFreedesktopScreenSaverProxyPrivate
{
  GData *qdata;
};

static void aa_dbus_freedesktop_screen_saver_proxy_iface_init (AADBusFreedesktopScreenSaverIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (AADBusFreedesktopScreenSaverProxy, aa_dbus_freedesktop_screen_saver_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (AADBusFreedesktopScreenSaverProxy)
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER, aa_dbus_freedesktop_screen_saver_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (AADBusFreedesktopScreenSaverProxy, aa_dbus_freedesktop_screen_saver_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER, aa_dbus_freedesktop_screen_saver_proxy_iface_init));

#endif
static void
aa_dbus_freedesktop_screen_saver_proxy_finalize (GObject *object)
{
  AADBusFreedesktopScreenSaverProxy *proxy = AA_DBUS_FREEDESKTOP_SCREEN_SAVER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (aa_dbus_freedesktop_screen_saver_proxy_parent_class)->finalize (object);
}

static void
aa_dbus_freedesktop_screen_saver_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
aa_dbus_freedesktop_screen_saver_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
aa_dbus_freedesktop_screen_saver_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_aa_dbus_freedesktop_screen_saver_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
aa_dbus_freedesktop_screen_saver_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  AADBusFreedesktopScreenSaverProxy *proxy = AA_DBUS_FREEDESKTOP_SCREEN_SAVER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_aa_dbus_freedesktop_screen_saver_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_aa_dbus_freedesktop_screen_saver_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
aa_dbus_freedesktop_screen_saver_proxy_init (AADBusFreedesktopScreenSaverProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = aa_dbus_freedesktop_screen_saver_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER_PROXY, AADBusFreedesktopScreenSaverProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), aa_dbus_freedesktop_screen_saver_interface_info ());
}

static void
aa_dbus_freedesktop_screen_saver_proxy_class_init (AADBusFreedesktopScreenSaverProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = aa_dbus_freedesktop_screen_saver_proxy_finalize;
  gobject_class->get_property = aa_dbus_freedesktop_screen_saver_proxy_get_property;
  gobject_class->set_property = aa_dbus_freedesktop_screen_saver_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = aa_dbus_freedesktop_screen_saver_proxy_g_signal;
  proxy_class->g_properties_changed = aa_dbus_freedesktop_screen_saver_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (AADBusFreedesktopScreenSaverProxyPrivate));
#endif
}

static void
aa_dbus_freedesktop_screen_saver_proxy_iface_init (AADBusFreedesktopScreenSaverIface *iface)
{
}

/**
 * aa_dbus_freedesktop_screen_saver_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call aa_dbus_freedesktop_screen_saver_proxy_new_finish() to get the result of the operation.
 *
 * See aa_dbus_freedesktop_screen_saver_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
aa_dbus_freedesktop_screen_saver_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ScreenSaver", NULL);
}

/**
 * aa_dbus_freedesktop_screen_saver_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to aa_dbus_freedesktop_screen_saver_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with aa_dbus_freedesktop_screen_saver_proxy_new().
 *
 * Returns: (transfer full) (type AADBusFreedesktopScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
AADBusFreedesktopScreenSaver *
aa_dbus_freedesktop_screen_saver_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return AA_DBUS_FREEDESKTOP_SCREEN_SAVER (ret);
  else
    return NULL;
}

/**
 * aa_dbus_freedesktop_screen_saver_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See aa_dbus_freedesktop_screen_saver_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type AADBusFreedesktopScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
AADBusFreedesktopScreenSaver *
aa_dbus_freedesktop_screen_saver_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ScreenSaver", NULL);
  if (ret != NULL)
    return AA_DBUS_FREEDESKTOP_SCREEN_SAVER (ret);
  else
    return NULL;
}


/**
 * aa_dbus_freedesktop_screen_saver_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like aa_dbus_freedesktop_screen_saver_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call aa_dbus_freedesktop_screen_saver_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See aa_dbus_freedesktop_screen_saver_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
aa_dbus_freedesktop_screen_saver_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ScreenSaver", NULL);
}

/**
 * aa_dbus_freedesktop_screen_saver_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to aa_dbus_freedesktop_screen_saver_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with aa_dbus_freedesktop_screen_saver_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type AADBusFreedesktopScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
AADBusFreedesktopScreenSaver *
aa_dbus_freedesktop_screen_saver_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return AA_DBUS_FREEDESKTOP_SCREEN_SAVER (ret);
  else
    return NULL;
}

/**
 * aa_dbus_freedesktop_screen_saver_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like aa_dbus_freedesktop_screen_saver_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See aa_dbus_freedesktop_screen_saver_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type AADBusFreedesktopScreenSaverProxy): The constructed proxy object or %NULL if @error is set.
 */
AADBusFreedesktopScreenSaver *
aa_dbus_freedesktop_screen_saver_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ScreenSaver", NULL);
  if (ret != NULL)
    return AA_DBUS_FREEDESKTOP_SCREEN_SAVER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * AADBusFreedesktopScreenSaverSkeleton:
 *
 * The #AADBusFreedesktopScreenSaverSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * AADBusFreedesktopScreenSaverSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #AADBusFreedesktopScreenSaverSkeleton.
 */

struct _AADBusFreedesktopScreenSaverSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_aa_dbus_freedesktop_screen_saver_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  AADBusFreedesktopScreenSaverSkeleton *skeleton = AA_DBUS_FREEDESKTOP_SCREEN_SAVER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_aa_dbus_freedesktop_screen_saver_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  AADBusFreedesktopScreenSaverSkeleton *skeleton = AA_DBUS_FREEDESKTOP_SCREEN_SAVER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_aa_dbus_freedesktop_screen_saver_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_aa_dbus_freedesktop_screen_saver_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  AADBusFreedesktopScreenSaverSkeleton *skeleton = AA_DBUS_FREEDESKTOP_SCREEN_SAVER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_aa_dbus_freedesktop_screen_saver_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _aa_dbus_freedesktop_screen_saver_skeleton_vtable =
{
  _aa_dbus_freedesktop_screen_saver_skeleton_handle_method_call,
  _aa_dbus_freedesktop_screen_saver_skeleton_handle_get_property,
  _aa_dbus_freedesktop_screen_saver_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
aa_dbus_freedesktop_screen_saver_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return aa_dbus_freedesktop_screen_saver_interface_info ();
}

static GDBusInterfaceVTable *
aa_dbus_freedesktop_screen_saver_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_aa_dbus_freedesktop_screen_saver_skeleton_vtable;
}

static GVariant *
aa_dbus_freedesktop_screen_saver_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  AADBusFreedesktopScreenSaverSkeleton *skeleton = AA_DBUS_FREEDESKTOP_SCREEN_SAVER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_aa_dbus_freedesktop_screen_saver_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _aa_dbus_freedesktop_screen_saver_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _aa_dbus_freedesktop_screen_saver_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _aa_dbus_freedesktop_screen_saver_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ScreenSaver", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
aa_dbus_freedesktop_screen_saver_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_aa_dbus_freedesktop_screen_saver_on_signal_active_changed (
    AADBusFreedesktopScreenSaver *object,
    gboolean arg_active)
{
  AADBusFreedesktopScreenSaverSkeleton *skeleton = AA_DBUS_FREEDESKTOP_SCREEN_SAVER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(b)",
                   arg_active));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ScreenSaver", "ActiveChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void aa_dbus_freedesktop_screen_saver_skeleton_iface_init (AADBusFreedesktopScreenSaverIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (AADBusFreedesktopScreenSaverSkeleton, aa_dbus_freedesktop_screen_saver_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (AADBusFreedesktopScreenSaverSkeleton)
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER, aa_dbus_freedesktop_screen_saver_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (AADBusFreedesktopScreenSaverSkeleton, aa_dbus_freedesktop_screen_saver_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER, aa_dbus_freedesktop_screen_saver_skeleton_iface_init));

#endif
static void
aa_dbus_freedesktop_screen_saver_skeleton_finalize (GObject *object)
{
  AADBusFreedesktopScreenSaverSkeleton *skeleton = AA_DBUS_FREEDESKTOP_SCREEN_SAVER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (aa_dbus_freedesktop_screen_saver_skeleton_parent_class)->finalize (object);
}

static void
aa_dbus_freedesktop_screen_saver_skeleton_init (AADBusFreedesktopScreenSaverSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = aa_dbus_freedesktop_screen_saver_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER_SKELETON, AADBusFreedesktopScreenSaverSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
aa_dbus_freedesktop_screen_saver_skeleton_class_init (AADBusFreedesktopScreenSaverSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = aa_dbus_freedesktop_screen_saver_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = aa_dbus_freedesktop_screen_saver_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = aa_dbus_freedesktop_screen_saver_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = aa_dbus_freedesktop_screen_saver_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = aa_dbus_freedesktop_screen_saver_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (AADBusFreedesktopScreenSaverSkeletonPrivate));
#endif
}

static void
aa_dbus_freedesktop_screen_saver_skeleton_iface_init (AADBusFreedesktopScreenSaverIface *iface)
{
  iface->active_changed = _aa_dbus_freedesktop_screen_saver_on_signal_active_changed;
}

/**
 * aa_dbus_freedesktop_screen_saver_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link>.
 *
 * Returns: (transfer full) (type AADBusFreedesktopScreenSaverSkeleton): The skeleton object.
 */
AADBusFreedesktopScreenSaver *
aa_dbus_freedesktop_screen_saver_skeleton_new (void)
{
  return AA_DBUS_FREEDESKTOP_SCREEN_SAVER (g_object_new (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for Object, ObjectProxy and ObjectSkeleton
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:AADBusObject
 * @title: AADBusObject
 * @short_description: Specialized GDBusObject types
 *
 * This section contains the #AADBusObject, #AADBusObjectProxy, and #AADBusObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces.
 */

/**
 * AADBusObject:
 *
 * The #AADBusObject type is a specialized container of interfaces.
 */

/**
 * AADBusObjectIface:
 * @parent_iface: The parent interface.
 *
 * Virtual table for the #AADBusObject interface.
 */

typedef AADBusObjectIface AADBusObjectInterface;
G_DEFINE_INTERFACE_WITH_CODE (AADBusObject, aa_dbus_object, G_TYPE_OBJECT, g_type_interface_add_prerequisite (g_define_type_id, G_TYPE_DBUS_OBJECT));

static void
aa_dbus_object_default_init (AADBusObjectIface *iface)
{
  /**
   * AADBusObject:gnome-screen-saver:
   *
   * The #AADBusGnomeScreenSaver instance corresponding to the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("gnome-screen-saver", "gnome-screen-saver", "gnome-screen-saver", AA_DBUS_TYPE_GNOME_SCREEN_SAVER, G_PARAM_READWRITE|G_PARAM_STATIC_STRINGS));

  /**
   * AADBusObject:freedesktop-screen-saver:
   *
   * The #AADBusFreedesktopScreenSaver instance corresponding to the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("freedesktop-screen-saver", "freedesktop-screen-saver", "freedesktop-screen-saver", AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER, G_PARAM_READWRITE|G_PARAM_STATIC_STRINGS));

}

/**
 * aa_dbus_object_get_gnome_screen_saver:
 * @object: A #AADBusObject.
 *
 * Gets the #AADBusGnomeScreenSaver instance for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link> on @object, if any.
 *
 * Returns: (transfer full): A #AADBusGnomeScreenSaver that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
AADBusGnomeScreenSaver *aa_dbus_object_get_gnome_screen_saver (AADBusObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.gnome.ScreenSaver");
  if (ret == NULL)
    return NULL;
  return AA_DBUS_GNOME_SCREEN_SAVER (ret);
}

/**
 * aa_dbus_object_get_freedesktop_screen_saver:
 * @object: A #AADBusObject.
 *
 * Gets the #AADBusFreedesktopScreenSaver instance for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link> on @object, if any.
 *
 * Returns: (transfer full): A #AADBusFreedesktopScreenSaver that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
AADBusFreedesktopScreenSaver *aa_dbus_object_get_freedesktop_screen_saver (AADBusObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.freedesktop.ScreenSaver");
  if (ret == NULL)
    return NULL;
  return AA_DBUS_FREEDESKTOP_SCREEN_SAVER (ret);
}


/**
 * aa_dbus_object_peek_gnome_screen_saver: (skip)
 * @object: A #AADBusObject.
 *
 * Like aa_dbus_object_get_gnome_screen_saver() but doesn't increase the reference count on the returned object.
 *
 * <warning>It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.</warning>
 *
 * Returns: (transfer none): A #AADBusGnomeScreenSaver or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
AADBusGnomeScreenSaver *aa_dbus_object_peek_gnome_screen_saver (AADBusObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.gnome.ScreenSaver");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return AA_DBUS_GNOME_SCREEN_SAVER (ret);
}

/**
 * aa_dbus_object_peek_freedesktop_screen_saver: (skip)
 * @object: A #AADBusObject.
 *
 * Like aa_dbus_object_get_freedesktop_screen_saver() but doesn't increase the reference count on the returned object.
 *
 * <warning>It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.</warning>
 *
 * Returns: (transfer none): A #AADBusFreedesktopScreenSaver or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
AADBusFreedesktopScreenSaver *aa_dbus_object_peek_freedesktop_screen_saver (AADBusObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.freedesktop.ScreenSaver");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return AA_DBUS_FREEDESKTOP_SCREEN_SAVER (ret);
}


static void
aa_dbus_object_notify (GDBusObject *object, GDBusInterface *interface)
{
  _ExtendedGDBusInterfaceInfo *info = (_ExtendedGDBusInterfaceInfo *) g_dbus_interface_get_info (interface);
  /* info can be NULL if the other end is using a D-Bus interface we don't know
   * anything about, for example old generated code in this process talking to
   * newer generated code in the other process. */
  if (info != NULL)
    g_object_notify (G_OBJECT (object), info->hyphen_name);
}

/**
 * AADBusObjectProxy:
 *
 * The #AADBusObjectProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * AADBusObjectProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #AADBusObjectProxy.
 */

static void
aa_dbus_object_proxy__aa_dbus_object_iface_init (AADBusObjectIface *iface G_GNUC_UNUSED)
{
}

static void
aa_dbus_object_proxy__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = aa_dbus_object_notify;
  iface->interface_removed = aa_dbus_object_notify;
}


G_DEFINE_TYPE_WITH_CODE (AADBusObjectProxy, aa_dbus_object_proxy, G_TYPE_DBUS_OBJECT_PROXY,
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_OBJECT, aa_dbus_object_proxy__aa_dbus_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, aa_dbus_object_proxy__g_dbus_object_iface_init));

static void
aa_dbus_object_proxy_init (AADBusObjectProxy *object G_GNUC_UNUSED)
{
}

static void
aa_dbus_object_proxy_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value G_GNUC_UNUSED,
  GParamSpec   *pspec)
{
  G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
}

static void
aa_dbus_object_proxy_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  AADBusObjectProxy *object = AA_DBUS_OBJECT_PROXY (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.gnome.ScreenSaver");
      g_value_take_object (value, interface);
      break;

    case 2:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.freedesktop.ScreenSaver");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
aa_dbus_object_proxy_class_init (AADBusObjectProxyClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = aa_dbus_object_proxy_set_property;
  gobject_class->get_property = aa_dbus_object_proxy_get_property;

  g_object_class_override_property (gobject_class, 1, "gnome-screen-saver");
  g_object_class_override_property (gobject_class, 2, "freedesktop-screen-saver");
}

/**
 * aa_dbus_object_proxy_new:
 * @connection: A #GDBusConnection.
 * @object_path: An object path.
 *
 * Creates a new proxy object.
 *
 * Returns: (transfer full): The proxy object.
 */
AADBusObjectProxy *
aa_dbus_object_proxy_new (GDBusConnection *connection,
  const gchar *object_path)
{
  g_return_val_if_fail (G_IS_DBUS_CONNECTION (connection), NULL);
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return AA_DBUS_OBJECT_PROXY (g_object_new (AA_DBUS_TYPE_OBJECT_PROXY, "g-connection", connection, "g-object-path", object_path, NULL));
}

/**
 * AADBusObjectSkeleton:
 *
 * The #AADBusObjectSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * AADBusObjectSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #AADBusObjectSkeleton.
 */

static void
aa_dbus_object_skeleton__aa_dbus_object_iface_init (AADBusObjectIface *iface G_GNUC_UNUSED)
{
}


static void
aa_dbus_object_skeleton__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = aa_dbus_object_notify;
  iface->interface_removed = aa_dbus_object_notify;
}

G_DEFINE_TYPE_WITH_CODE (AADBusObjectSkeleton, aa_dbus_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON,
                         G_IMPLEMENT_INTERFACE (AA_DBUS_TYPE_OBJECT, aa_dbus_object_skeleton__aa_dbus_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, aa_dbus_object_skeleton__g_dbus_object_iface_init));

static void
aa_dbus_object_skeleton_init (AADBusObjectSkeleton *object G_GNUC_UNUSED)
{
}

static void
aa_dbus_object_skeleton_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  AADBusObjectSkeleton *object = AA_DBUS_OBJECT_SKELETON (gobject);
  GDBusInterfaceSkeleton *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (AA_DBUS_IS_GNOME_SCREEN_SAVER (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "org.gnome.ScreenSaver");
        }
      break;

    case 2:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (AA_DBUS_IS_FREEDESKTOP_SCREEN_SAVER (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "org.freedesktop.ScreenSaver");
        }
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
aa_dbus_object_skeleton_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  AADBusObjectSkeleton *object = AA_DBUS_OBJECT_SKELETON (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.gnome.ScreenSaver");
      g_value_take_object (value, interface);
      break;

    case 2:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.freedesktop.ScreenSaver");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
aa_dbus_object_skeleton_class_init (AADBusObjectSkeletonClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = aa_dbus_object_skeleton_set_property;
  gobject_class->get_property = aa_dbus_object_skeleton_get_property;

  g_object_class_override_property (gobject_class, 1, "gnome-screen-saver");
  g_object_class_override_property (gobject_class, 2, "freedesktop-screen-saver");
}

/**
 * aa_dbus_object_skeleton_new:
 * @object_path: An object path.
 *
 * Creates a new skeleton object.
 *
 * Returns: (transfer full): The skeleton object.
 */
AADBusObjectSkeleton *
aa_dbus_object_skeleton_new (const gchar *object_path)
{
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return AA_DBUS_OBJECT_SKELETON (g_object_new (AA_DBUS_TYPE_OBJECT_SKELETON, "g-object-path", object_path, NULL));
}

/**
 * aa_dbus_object_skeleton_set_gnome_screen_saver:
 * @object: A #AADBusObjectSkeleton.
 * @interface_: (allow-none): A #AADBusGnomeScreenSaver or %NULL to clear the interface.
 *
 * Sets the #AADBusGnomeScreenSaver instance for the D-Bus interface <link linkend="gdbus-interface-org-gnome-ScreenSaver.top_of_page">org.gnome.ScreenSaver</link> on @object.
 */
void aa_dbus_object_skeleton_set_gnome_screen_saver (AADBusObjectSkeleton *object, AADBusGnomeScreenSaver *interface_)
{
  g_object_set (G_OBJECT (object), "gnome-screen-saver", interface_, NULL);
}

/**
 * aa_dbus_object_skeleton_set_freedesktop_screen_saver:
 * @object: A #AADBusObjectSkeleton.
 * @interface_: (allow-none): A #AADBusFreedesktopScreenSaver or %NULL to clear the interface.
 *
 * Sets the #AADBusFreedesktopScreenSaver instance for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ScreenSaver.top_of_page">org.freedesktop.ScreenSaver</link> on @object.
 */
void aa_dbus_object_skeleton_set_freedesktop_screen_saver (AADBusObjectSkeleton *object, AADBusFreedesktopScreenSaver *interface_)
{
  g_object_set (G_OBJECT (object), "freedesktop-screen-saver", interface_, NULL);
}


/* ------------------------------------------------------------------------
 * Code for ObjectManager client
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:AADBusObjectManagerClient
 * @title: AADBusObjectManagerClient
 * @short_description: Generated GDBusObjectManagerClient type
 *
 * This section contains a #GDBusObjectManagerClient that uses aa_dbus_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc.
 */

/**
 * AADBusObjectManagerClient:
 *
 * The #AADBusObjectManagerClient structure contains only private data and should only be accessed using the provided API.
 */

/**
 * AADBusObjectManagerClientClass:
 * @parent_class: The parent class.
 *
 * Class structure for #AADBusObjectManagerClient.
 */

G_DEFINE_TYPE (AADBusObjectManagerClient, aa_dbus_object_manager_client, G_TYPE_DBUS_OBJECT_MANAGER_CLIENT);

static void
aa_dbus_object_manager_client_init (AADBusObjectManagerClient *manager G_GNUC_UNUSED)
{
}

static void
aa_dbus_object_manager_client_class_init (AADBusObjectManagerClientClass *klass G_GNUC_UNUSED)
{
}

/**
 * aa_dbus_object_manager_client_get_proxy_type:
 * @manager: A #GDBusObjectManagerClient.
 * @object_path: The object path of the remote object (unused).
 * @interface_name: (allow-none): Interface name of the remote object or %NULL to get the object proxy #GType.
 * @user_data: User data (unused).
 *
 * A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy<!-- -->- and #GDBusProxy<!-- -->-derived types.
 *
 * Returns: A #GDBusProxy<!-- -->-derived #GType if @interface_name is not %NULL, otherwise the #GType for #AADBusObjectProxy.
 */
GType
aa_dbus_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar *interface_name, gpointer user_data G_GNUC_UNUSED)
{
  static gsize once_init_value = 0;
  static GHashTable *lookup_hash;
  GType ret;

  if (interface_name == NULL)
    return AA_DBUS_TYPE_OBJECT_PROXY;
  if (g_once_init_enter (&once_init_value))
    {
      lookup_hash = g_hash_table_new (g_str_hash, g_str_equal);
      g_hash_table_insert (lookup_hash, (gpointer) "org.gnome.ScreenSaver", GSIZE_TO_POINTER (AA_DBUS_TYPE_GNOME_SCREEN_SAVER_PROXY));
      g_hash_table_insert (lookup_hash, (gpointer) "org.freedesktop.ScreenSaver", GSIZE_TO_POINTER (AA_DBUS_TYPE_FREEDESKTOP_SCREEN_SAVER_PROXY));
      g_once_init_leave (&once_init_value, 1);
    }
  ret = (GType) GPOINTER_TO_SIZE (g_hash_table_lookup (lookup_hash, interface_name));
  if (ret == (GType) 0)
    ret = G_TYPE_DBUS_PROXY;
  return ret;
}

/**
 * aa_dbus_object_manager_client_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates #GDBusObjectManagerClient using aa_dbus_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call aa_dbus_object_manager_client_new_finish() to get the result of the operation.
 *
 * See aa_dbus_object_manager_client_new_sync() for the synchronous, blocking version of this constructor.
 */
void
aa_dbus_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (AA_DBUS_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", aa_dbus_object_manager_client_get_proxy_type, NULL);
}

/**
 * aa_dbus_object_manager_client_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to aa_dbus_object_manager_client_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with aa_dbus_object_manager_client_new().
 *
 * Returns: (transfer full) (type AADBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
aa_dbus_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * aa_dbus_object_manager_client_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates #GDBusObjectManagerClient using aa_dbus_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See aa_dbus_object_manager_client_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type AADBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
aa_dbus_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (AA_DBUS_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", aa_dbus_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/**
 * aa_dbus_object_manager_client_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like aa_dbus_object_manager_client_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call aa_dbus_object_manager_client_new_for_bus_finish() to get the result of the operation.
 *
 * See aa_dbus_object_manager_client_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
aa_dbus_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (AA_DBUS_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", aa_dbus_object_manager_client_get_proxy_type, NULL);
}

/**
 * aa_dbus_object_manager_client_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to aa_dbus_object_manager_client_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with aa_dbus_object_manager_client_new_for_bus().
 *
 * Returns: (transfer full) (type AADBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
aa_dbus_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * aa_dbus_object_manager_client_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like aa_dbus_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See aa_dbus_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type AADBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
aa_dbus_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (AA_DBUS_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", aa_dbus_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


